joy_actions:

  secure:
    id: left_shoulder

  take_off:
    id: x

  land:
    id: b

  toggle_headless:
    id: right_shoulder

  speed_down:
    id: left_trigger

  speed_up:
    id: right_trigger

  throttle:
    id: left_analog_y
    reversed: false

  yaw:
    id: left_analog_x
    reversed: false

  pitch:
    id: right_analog_y
    reversed: false

  roll:
    id: right_analog_x
    reversed: false
